# Generated by Django 5.0.7 on 2024-10-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='project name')),
                ('description', models.TextField(verbose_name='About project')),
            ],
        ),
        migrations.RenameModel(
            old_name='client',
            new_name='skill',
        ),
        migrations.DeleteModel(
            name='service',
        ),
    ]
